### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'shape'

### ISSUE THREAD

**Issue by Gogolooklook** [pypa/packaging#151]
> Using TensorFlow backend.
2018-11-27 19:19:40.819599: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Now we build the Actor model
/home/lkx/下载/DRL/ActorNetwork.py:65: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(91, name="a_h0", activation=<function ..., kernel_initializer=<function ...)`
  h0 = Dense(self.HIDDEN1_UNITS, activation=self.h_acti, init=glorot_normal, name='a_h0')(S)
Traceback (most recent call last):
  File "ddpg.py", line 216, in <module>
    playGame(DDPG_config, train_indicator=1)
  File "ddpg.py", line 75, in playGame
    actor = ActorNetwork(sess, state_dim, action_dim, DDPG_config)
  File "/home/lkx/下载/DRL/ActorNetwork.py", line 41, in __init__
    self.model, self.weights, self.state = self.create_actor_network(state_size, action_size)
  File "/home/lkx/下载/DRL/ActorNetwork.py", line 65, in create_actor_network
    h0 = Dense(self.HIDDEN1_UNITS, activation=self.h_acti, init=glorot_normal, name='a_h0')(S)
  File "/home/lkx/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/home/lkx/.local/lib/python3.5/site-packages/keras/layers/core.py", line 866, in build
    constraint=self.kernel_constraint)
  File "/home/lkx/.local/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/lkx/.local/lib/python3.5/site-packages/keras/engine/base_layer.py", line 252, in add_weight
    constraint=constraint)
  File "/home/lkx/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 402, in variable
    v = tf.Variable(value, dtype=tf.as_dtype(dtype), name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 183, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 146, in _variable_v1_call
    aggregation=aggregation)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 125, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variable_scope.py", line 2444, in default_variable_creator
    expected_shape=expected_shape, import_scope=import_scope)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 187, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 1329, in __init__
    constraint=constraint)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/variables.py", line 1437, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
TypeError: __call__() missing 1 required positional argument: 'shape'

> I just run the http://knowledgedefinednetworking.org/ DRL, what should i do ?

**Comment by di** [comment]
This is not the right place for this issue, you probably want the [Tensorflow issue tracker](https://github.com/tensorflow/tensorflow/issues) instead.

**Comment by lxsky-crypto** [comment]
Have you solved this problem? Could you tell me?
