### ISSUE TITLE
--no-cache-dir broken in pip 19.0

### ISSUE THREAD

**Issue by neilvana** [pypa/packaging#159]
With the release of pip 19.0, the --no-cache-dir option seems to no longer work.  Running something as simple as:
`pip install --no-cache-dir requests`

 fails with the following exception:

```
Collecting requests
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 3.9MB/s
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\program files\python37\lib\site-packages (from requests) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python37\lib\site-packages (from requests) (2018.11.29)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\program files\python37\lib\site-packages (from requests) (1.24.1)
Requirement already satisfied: idna<2.9,>=2.5 in c:\program files\python37\lib\site-packages (from requests) (2.8)
Exception:
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 176, in main
    status = self.run(options, args)
  File "c:\program files\python37\lib\site-packages\pip\_internal\commands\install.py", line 346, in run
    session=session, autobuilding=True
  File "c:\program files\python37\lib\site-packages\pip\_internal\wheel.py", line 848, in build
    assert building_is_possible
AssertionError
```

I have tested this fails on Windows with both Python 2.7 and Python 3.7.

**Comment by neilvana** [comment]
Sorry, I think I filed this in the wrong place.  This should be closed in favor of https://github.com/pypa/pip/issues/6158
