### ISSUE TITLE
ImportWarning: VendorImporter.exec_module() not found; falling back to load_module()

### ISSUE THREAD

**Issue by blueyed** [pypa/packaging#375]
With Python 3.10-dev (since https://github.com/python/cpython/commit/2de5097ba4 (https://github.com/python/cpython/pull/23469)) an ImportWarning is issued when `exec_module` is missing.

```
% python -Werror -c 'import pkg_resources'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 73, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 1026, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1005, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 681, in _load_unlocked
ImportWarning: VendorImporter.exec_module() not found; falling back to load_module()

```
Package    Version
---------- -------
packaging  20.8
pip        20.3.3
pyparsing  2.4.7
setuptools 51.0.0

Python 3.10.0a3+ (heads/master:c56f9df049, Dec 19 2020, 19:50:13)
```

**Comment by blueyed** [comment]
Sorry for mixing this up, this is https://github.com/pypa/setuptools/issues/2481.
