### ISSUE TITLE
DeprecationWarning: distutils package is deprecated and slated for removal

### ISSUE THREAD

**Issue by jaraco** [pypa/packaging#433]
```
$ python3.10 -m pip-run packaging==20.9 -- -W error -c "import packaging.tags"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/packaging/tags.py", line 7, in <module>
    import distutils.util
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/__init__.py", line 19, in <module>
    warnings.warn(_DEPRECATION_MESSAGE,
DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
```

**Comment by uranusjr** [comment]
Already fixed in #396.
