### ISSUE TITLE
Requirement fails to handle requirements in hash-checking mode

### ISSUE THREAD

**Issue by mmaitre314** [pypa/packaging#488]
`Requirement` fails to parse requirement strings containing packages hashes `--hash=sha256:xxx`. Is the expectation that `Requirement` should handle those or the caller to `Requirement` should remove them before the call?

Using the example from https://pip.pypa.io/en/latest/cli/pip_install/#hash-checking-mode:

```
>>> from packaging.requirements import Requirement
>>> Requirement("FooProject == 1.2")
<Requirement('FooProject==1.2')>
>>> Requirement("FooProject == 1.2 --hash=sha256:2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824")
Traceback (most recent call last):
  File "C:\Users\mmaitre\Anaconda3\envs\local_training_mlflow_project\lib\site-packages\packaging\requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\Users\mmaitre\Anaconda3\envs\local_training_mlflow_project\lib\site-packages\pyparsing.py", line 1955, in parseString
    raise exc
  File "C:\Users\mmaitre\Anaconda3\envs\local_training_mlflow_project\lib\site-packages\pyparsing.py", line 3814, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected stringEnd, found '-'  (at char 18), (line:1, col:19)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mmaitre\Anaconda3\envs\local_training_mlflow_project\lib\site-packages\packaging\requirements.py", line 104, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'--hash=s'": Expected stringEnd
```

Version: `packaging==21.0`

Impacted issue: https://github.com/mlflow/mlflow/issues/4886

**Comment by pradyunsg** [comment]
That is a pip-specific feature. See https://pip.pypa.io/en/stable/reference/requirements-file-format/ for details on that format.

This package implements parsers and helpers for cross-tool interoperability standards (like https://www.python.org/dev/peps/pep-0508/, in this case).
