### ISSUE TITLE
Distutils was imported before Setuptools

### ISSUE THREAD

**Issue by ThomasSteinbach** [pypa/packaging#506]
When installing `setuptools-git-versioning` I also upgraded `packaging` implicitly from `20.9` to `21.3`. Since then I get following error when running `pipenv-setup check`:

```
(gitlab-ci-python-library) bash-3.2$ pipenv-setup check
/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/_distutils_hack/__init__.py:18: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
  "Distutils was imported before Setuptools, but importing Setuptools "
/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Traceback (most recent call last):
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/bin/pipenv-setup", line 5, in <module>
    from pipenv_setup.main import cmd
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/pipenv_setup/main.py", line 20, in <module>
    from pipenv_setup import (
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/pipenv_setup/lockfile_parser.py", line 3, in <module>
    from requirementslib import Lockfile, Requirement
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/requirementslib/__init__.py", line 7, in <module>
    from .models.lockfile import Lockfile
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/requirementslib/models/lockfile.py", line 16, in <module>
    from .requirements import Requirement
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/requirementslib/models/requirements.py", line 51, in <module>
    from .setup_info import (
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/requirementslib/models/setup_info.py", line 50, in <module>
    from setuptools.dist import Distribution, distutils
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 71, in do_override
    ensure_local_distutils()
  File "/Users/thomass/.local/share/virtualenvs/gitlab-ci-python-library-QTvEvI_g/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /Users/thomass/.pyenv/versions/3.7.12/lib/python3.7/distutils/core.py
```

When downgrading packaging back to `20.9` the error disappears.

-----

Here my current Pipfile if required. It already pinned packaging to `20.9`.

```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
boto3 = "~=1.17"
pyaml = ">=20"
packaging = "~=20.9"
setuptools-git-versioning = "*"

[dev-packages]
pytest = "*"
black = "*"
isort = "*"
flake8 = "*"
mypy = "*"
pytest-cov = "*"
pytest-mock = "*"
pipenv-setup = "*"

[requires]
python_version = "3.7"
```

**Comment by brettcannon** [comment]
We actually don't import distutils anywhere in our code base except in our `setup.py` script. We also are not in that traceback. My suspicion is upgrading us is upgrading something else that is causing the failure.

So unfortunately I don't think we can help you as we are not the direct trigger of this. To try and diagnose this, you can run Python with `-v` to see all imports that occur and then search for the first bit of code to import `distutils`.
