### ISSUE TITLE
Present a clearer error message when the user misses a space before `;` in marker

### ISSUE THREAD

**Issue by pradyunsg** [pypa/packaging#529]
Currently, if you try to use:

```
tomli @ https://github.com/hukkin/tomli/archive/master.zip; python_version < '3.11'
```

The error you get is:

```py
>>> Requirement("tomli @ https://github.com/hukkin/tomli/archive/master.zip; python_version < '3.11'")
Traceback (most recent call last):
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected string_end, found 'python'  (at char 60), (line:1, col:61)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'python_v'": Expected string_end
```

It would be good if it presented an error that suggested adding a ` ` (space) before the semicolon.

**Comment by pradyunsg** [comment]
In #624, these cases get an error like:

```
packaging.requirements.InvalidRequirement: Expected end or semicolon (after URL and whitespace)
    package @ https://example.com/; python_version <= '3.2'
              ~~~~~~~~~~~~~~~~~~~~~^
```

**Comment by Jackenmen** [comment]
Could the arrow's position be adjusted so that it points at the semicolon's position (since that's where the space is missing)? I think that it pointing at the first letter of the marker is confusing.

// #592 also hints directly that it might be the space between URL and semicolon that's missing while in your error it IMO seems a bit less clear. But I guess users will probably be able to figure it out just fine anyway so I wouldn't say it's a big deal.

**Comment by pradyunsg** [comment]
Yea, I flip-flopped on that aspect (I _think_ that might actually be visible in the force-push history), and ended up on this style since it was consistent with how "bad" versions specifiers ended up being handled:

```
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
     name ==0.this.is.a.bad.version ; python_version == "1.0"
          ~~~^
```

**Comment by pradyunsg** [comment]
Granted all of the options we have at hand are improvements over:

```
packaging.requirements.InvalidRequirement: Parse error at "'python_v'": Expected string_end
```
