### ISSUE TITLE
ImportError: cannot import name api_helpers

### ISSUE THREAD

**Issue by soso25** [pypa/packaging#59]
Hello,

it 's been almost a day I try to run my function "regina.py", but I can not get this makes me errors like this:

>>> import regina.py
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/Sokhna/Documents/mgp-test-i11vf/regina.py", line 13, in <module>
    import diane
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/Sokhna/Documents/mgp-test-i11vf/diane.py", line 19, in <module>
    import nayru
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/Sokhna/Documents/mgp-test-i11vf/nayru.py", line 1, in <module>
    import falcon
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/falcon/__init__.py", line 32, in <module>
    from falcon.api import API, DEFAULT_MEDIA_TYPE  # NOQA
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/falcon/api.py", line 18, in <module>
    from falcon import api_helpers as helpers
ImportError: cannot import name api_helpers

I just started python and there I am disappointed because I don't understand anything.

Can anyone help me please :( :( :(

**Comment by dstufft** [comment]
I'm not sure how you found this repository, but this doesn't appear to be related to the pypa/packaging project at all. I think perhaps you're looking for the falcon project?

**Comment by soso25** [comment]
yes okay i'm sorry
