### ISSUE TITLE
`Requirement('installer')` errors after 2bd5da391c302f2f5a18fd3e2bd9fb3b75c02e34

### ISSUE THREAD

**Issue by KOLANICH** [pypa/packaging#618]
```python
from packaging.requirements import Requirement
Requirement('installer')
```

The regression has been introduced in [2bd5da391c302f2f5a18fd3e2bd9fb3b75c02e34](https://github.com/pypa/packaging/commit/2e5593c1288b9f1b57bb1f79acc0ed5fd1b7009c).

**Comment by KOLANICH** [comment]
Sorry, not 2bd5da391c302f2f5a18fd3e2bd9fb3b75c02e34, but 2e5593c1288b9f1b57bb1f79acc0ed5fd1b7009c

**Comment by pradyunsg** [comment]
OK, I spent a bit of time looking at trying to fuzz our tests for the tokeniser with hypothesis, but I've hit multiple issues with trying to use hypothesis/hypofuzz at this point.

It's really cool tho, especially with the pytrace integration. :)

**Comment by pradyunsg** [comment]
FWIW, #619 has been significantly increased in size and scope.

**Comment by pradyunsg** [comment]
Well, here's another regression:

```sh-session
❯ python -c "import packaging; print(packaging.__version__); from packaging.requirements import Requirement; print(vars(Requirement(\"  name == 3.0.*  \")))"
21.4.dev0
IDENTIFIER   name
OP  ==
VERSION  3.0.*
Traceback (most recent call last):
  File "/Users/pradyunsg/Developer/github/packaging/packaging/requirements.py", line 35, in __init__
    req = parse_named_requirement(requirement_string)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_parser.py", line 79, in parse_named_requirement
    specifier = parse_specifier(tokens)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_parser.py", line 119, in parse_specifier
    parsed_specifiers = parse_version_many(tokens)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_parser.py", line 136, in parse_version_many
    if not tokens.match("COMMA"):
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_tokenizer.py", line 102, in match
    token = self.peek()
            ^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_tokenizer.py", line 95, in peek
    self.next_token = next(self.generator)
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_tokenizer.py", line 163, in _tokenize
    raise self.raise_syntax_error(message="Unrecognized token")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_tokenizer.py", line 138, in raise_syntax_error
    raise ParseExceptionError(
packaging._tokenizer.ParseExceptionError: Unrecognized token
at position 15:
      name == 3.0.*  
                   ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pradyunsg/Developer/github/packaging/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e))
packaging.requirements.InvalidRequirement: Unrecognized token
at position 15:
      name == 3.0.*  
                   ^
❯ python -c "import packaging; print(packaging.__version__); from packaging.requirements import Requirement; print(vars(Requirement(\"  name == 3.0.*  \")))"
21.3
{'name': 'name', 'url': None, 'extras': set(), 'specifier': <SpecifierSet('==3.0.*')>, 'marker': None}
```

**Comment by pradyunsg** [comment]
I've started a parser rewrite, to couple the parsing and tokenising such that tokenising is context-sensitive.

**Comment by hrnciar** [comment]
I apologise for the issues that caused my contribution. I'd be happy to address them had I known about them. Since nobody mentioned me sooner, I learned about the problems during the weekend after @pradyunsg already spend time rewriting it and opened #624.

**Comment by pradyunsg** [comment]
@hrnciar There's no need to apologise. My work in that PR is very-much based off of your work, and I certainly wouldn't have gotten as far as I have without the existing base that you built! :)

I was already looking improving the error messages around requirement parsing back (partly what motivated this parser rewrite), so it was fairly organic to dive into this for me.

**Comment by pradyunsg** [comment]
On a different note... what do we want to do with strings like:

```
package(===arbitrarystring)
```

The behaviours we have:

(21.3)

```sh-session
❯ echo "package(===arbitrarystring)" | python -c "import packaging; from packaging.requirements import Requirement; print(packaging.__version__); print(vars(Requirement(input())))"
21.3
Traceback (most recent call last):
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/pyparsing/core.py", line 1141, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected string_end, found '('  (at char 7), (line:1, col:8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
packaging.requirements.InvalidRequirement: Parse error at "'(===arbi'": Expected string_end
```

(main)

```sh-session
❯ echo "package(===arbitrarystring)" | python -c "import packaging; from packaging.requirements import Requirement; print(packaging.__version__); print(vars(Requirement(input())))"
21.4.dev0
Traceback (most recent call last):
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 35, in __init__
    req = parse_named_requirement(requirement_string)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/_parser.py", line 79, in parse_named_requirement
    specifier = parse_specifier(tokens)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/_parser.py", line 121, in parse_specifier
    tokens.raise_syntax_error(message="Closing right parenthesis is missing")
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/_tokenizer.py", line 138, in raise_syntax_error
    raise ParseExceptionError(
packaging._tokenizer.ParseExceptionError: Closing right parenthesis is missing
at position 27:
    package(===arbitrarystring)
                               ^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pradyunsg/Developer/github/packaging/.venv/lib/python3.11/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e))
packaging.requirements.InvalidRequirement: Closing right parenthesis is missing
at position 27:
    package(===arbitrarystring)
                               ^
```

And... I have two options:

(a) Error out:

```sh-session
❯ echo "package(===arbitrarystring)" | python -c "import packaging; from packaging.requirements import Requirement; print(packaging.__version__); print(vars(Requirement(input())))"
21.4.dev0
Traceback (most recent call last):
  File "/Users/pradyunsg/Developer/github/packaging/packaging/requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_parser.py", line 115, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_parser.py", line 196, in _parse_specifier
    with tokenizer.enclosing_tokens("LEFT_PARENTHESIS", "RIGHT_PARENTHESIS"):
  File "/Users/pradyunsg/.asdf/installs/python/3.11.0/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_tokenizer.py", line 181, in enclosing_tokens
    self.raise_syntax_error(
  File "/Users/pradyunsg/Developer/github/packaging/packaging/_tokenizer.py", line 161, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    package(===arbitrarystring)
           ~~~~~~~~~~~~~~~~~~~~^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/pradyunsg/Developer/github/packaging/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e))
packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    package(===arbitrarystring)
           ~~~~~~~~~~~~~~~~~~~~^
```

(b) Modify how `Specifier` parses arbitrary versions strings to parse this like `package ( === arbitrarystring )`

```sh-session
❯ echo "package(===arbitrarystring)" | python -c "import packaging; from packaging.requirements import Requirement; print(packaging.__version__); print(vars(Requirement(input())))"
21.4.dev0
{'name': 'package', 'url': None, 'extras': set(), 'specifier': <SpecifierSet('===arbitrarystring')>, 'marker': None}
```

**Comment by pradyunsg** [comment]
I'm inclined to go with option (b).

**Comment by pradyunsg** [comment]
The same situation as `)` happens with `;` for markers.

**Comment by brettcannon** [comment]
If someone messes up their specifier so it isn't valid, how will they know that with option (b)? Will it be based on the fact that the specifier will never be true?

**Comment by pradyunsg** [comment]
FWIW, [`39ae524` (#624)](https://github.com/pypa/packaging/pull/624/commits/39ae524488a6e7e436494d13dcef021d835a2a78) is the relevant change for fixing how this parses things.
