### ISSUE TITLE
Version 22.0 packaging breaks requirements.txt parsing

### ISSUE THREAD

**Issue by rikardn** [pypa/packaging#628]
I am not 100% sure but it seems as if the newly released version 22.0 of packaging breaks the parsing of some `requirements.txt`. A workflow that run well before the release now gets the error below. (See https://github.com/pharmpy/pharmpy/actions/runs/3644239173/jobs/6153288291 for full context). To me it looks like the tokenizer of `packaging` falls over. The problematic line (that used to work) in `requirements.txt` is: 

```
tflite_runtime @ https://github.com/hjonnala/snippets/raw/main/wheels/python3.10/tflite_runtime-2.5.0.post1-cp310-cp310-linux_x86_64.whl; sys_platform == 'linux' and python_version == '3.10'
```

```
unit: internal error
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\packaging\requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\packaging\_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\packaging\_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\packaging\_parser.py", line 111, in _parse_requirement_details
    marker = _parse_requirement_marker(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\packaging\_parser.py", line 143, in _parse_requirement_marker
    tokenizer.raise_syntax_error(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\packaging\_tokenizer.py", line 161, in raise_syntax_error
    raise ParserSyntaxError(
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after URL and whitespace)
    tflite_runtime @ https://github.com/hjonnala/snippets/raw/main/wheels/python3.10/tflite_runtime-2.5.0.post1-cp310-cp310-linux_x86_64.whl; sys_platform == 'linux' and python_version == '3.10'
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req\file.py", line 37, in __init__
    self._requirement: Requirement | Path | str = Requirement(req)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\packaging\requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after URL and whitespace)
    tflite_runtime @ https://github.com/hjonnala/snippets/raw/main/wheels/python3.10/tflite_runtime-2.5.0.post1-cp310-cp310-linux_x86_64.whl; sys_platform == 'linux' and python_version == '3.10'
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\session\cmd\run\single.py", line 45, in _evaluate
    tox_env.setup()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\api.py", line 226, in setup
    self._setup_env()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\runner.py", line 90, in _setup_env
    self._install_deps()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\runner.py", line 94, in _install_deps
    self.installer.install(requirements_file, PythonRun.__name__, "deps")
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\pip_install.py", line 84, in install
    self._install_requirement_file(arguments, section, of_type)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\pip_install.py", line 93, in _install_requirement_file
    new_options, new_reqs = arguments.unroll()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req_file.py", line 84, in unroll
    opts_dict = vars(self.options)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req\file.py", line 153, in options
    self._ensure_requirements_parsed()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req\file.py", line 169, in _ensure_requirements_parsed
    self._requirements = self._parse_requirements(opt=self._opt, recurse=True)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req_file.py", line 71, in _parse_requirements
    requirements = super()._parse_requirements(opt, recurse)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req\file.py", line 175, in _parse_requirements
    parsed_req = self._handle_requirement_line(parsed_line)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req\file.py", line 279, in _handle_requirement_line
    return ParsedRequirement(line.requirement, req_options, line.filename, line.lineno)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\tox\tox_env\python\pip\req\file.py", line 61, in __init__
    rel_path = str(path.resolve().relative_to(root))
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: "D:\\a\\pharmpy\\pharmpy\\tflite_runtime @ https:\\github.com\\hjonnala\\snippets\\raw\\main\\wheels\\python3.10\\tflite_runtime-2.5.0.post1-cp310-cp310-linux_x86_64.whl; sys_platform == 'linux' and python_version == '3.10'"
  unit: FAIL code 2 (1.11 seconds)
  evaluation failed :( (1.44 seconds)
Error: Process completed with exit code 2.
```

**Comment by uranusjr** [comment]
It’s not related to 22.0, this would have failed in earlier versions as well. See #529.

**Comment by rikardn** [comment]
It is indeed the same problem as in #529 and I could fix my `requirements.txt` and the workflow runs fine again. The reason this started to fail now is probably that there is also a new version of `tox` out. Thanks for helping me resolve this problem!
