### ISSUE TITLE
Comparing marker string with marker string

### ISSUE THREAD

**Issue by konstin** [pypa/packaging#632]
Currently comparing two marker string is legal in PEP 508, but fails in packaging 22.0:

```python
from packaging.requirements import Requirement
Requirement('numpy; "a" <= "b"').marker.evaluate()
Traceback (most recent call last):
  File "/home/konsti/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/223.7571.203/plugins/python/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/konsti/pep508/.venv/lib/python3.8/site-packages/packaging/markers.py", line 241, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/konsti/pep508/.venv/lib/python3.8/site-packages/packaging/markers.py", line 148, in _evaluate_markers
    rhs_value = environment[environment_key]
KeyError: 'b'
```

The two options are to make this legal in packaging or to that from the [Dependency specifiers](https://packaging.python.org/en/latest/specifications/dependency-specifiers) aka PEP 508, imho it the better option would be to just ban it

**Comment by konstin** [comment]
no, it just throws a different error

**Comment by pradyunsg** [comment]
Could you post that error as well?

**Comment by konstin** [comment]
Sure, i checked and in all versions down to 20.0 `numpy; "a" <= "b"` raises `packaging.markers.UndefinedEnvironmentName: 'b' does not exist in evaluation environment.`

**Comment by frostming** [comment]
If I interpret [PEP 508](https://peps.python.org/pep-0508/#environment-markers) correctly, these markers should be allowed:

```python
"a" == "b"
"a" <= "b"
```

While these are forbidden:
```python
"a" ~= "b"
```

**Comment by pradyunsg** [comment]
Bah, this isn’t a logical thing to do and I’d much rather we amend the dependency specification format to disallow such string comparisons and reject these markers.

**Comment by konstin** [comment]
I agree with @pradyunsg to change the spec. Imho the best thing would be to change the PEP 508 grammar to

```
marker_expr   = wsp* env_var wsp* marker_op wsp* python_str
              | wsp* python_str wsp* marker_op wsp* env_var
              | wsp* '(' marker wsp* ')'
```

This would also disallow other strange comparisons like `extra == os_name`.

(imho it should also be specified which `env_var` are PEP 440 and which are compared stringly, but that's a separate issue)

**Comment by henryiii** [comment]
This is no longer a crash, and the spec clarifies that it depends on the expected type (similar to how uv does it), packaging follows that since 26.1 +/- 0.1. Figuring out a proper tightening is still something that needs to be done.

**Comment by konstin** [comment]
From my perspective this can be closed with reference to the fixed spec.
