### ISSUE TITLE
Fails to parse requirement with trailing whitespace

### ISSUE THREAD

**Issue by gaborbernat** [pypa/packaging#649]
```python
from packaging.requirements import Requirement

req = "pycontracts @ https://github.com/slorg1/contracts/archive/c5a6da27d4dc9985f68e574d20d86000880919c3.zip "
Requirement(req)
```

```
packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after URL and whitespace)
    pycontracts @ https://github.com/slorg1/contracts/archive/c5a6da27d4dc9985f68e574d20d86000880919c3.zip 
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bgabor8/git/github/tox/magic.py", line 4, in <module>
    Requirement(req)
  File "/Users/bgabor8/git/github/tox/.tox/dev/lib/python3.11/site-packages/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected end or semicolon (after URL and whitespace)
    pycontracts @ https://github.com/slorg1/contracts/archive/c5a6da27d4dc9985f68e574d20d86000880919c3.zip 
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
```

Would you happen to know if this is expected? If you remove the trailing whitespace, the parsing succeeds. Parsing `attrs    ` works, so this is slightly unexpected. Initially reported via https://github.com/tox-dev/tox/issues/2773

**Comment by pradyunsg** [comment]
Covered by https://github.com/pypa/packaging/pull/642.
