### ISSUE TITLE
version.parse : exception during version parsing 

### ISSUE THREAD

**Issue by HarinadhD** [pypa/packaging#815]
Below code snippet is working fine with the  packaging version 21.3 , but throwing an error **"Invalid version"** on latest version (24.0 & 24.1) 

test.py
```
import` os,sys,subprocess
from decimal import Decimal
from packaging import version
str1='8.9p1-8'
str2='8.9p1-6'
if version.parse(str1) > version.parse(str2):
    print("OK")
```

**executing on version 24.0 & 24.1 :**
```
#python3 test.py
Traceback (most recent call last):
  File "/root/test.py", line 9, in <module>
    if version.parse(str1) > version.parse(str2):
       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '8.9p1-8'
```

**executing on version  21.3:**

#python3 test.py
OK

**Comment by HarinadhD** [comment]
This behaviour is observed from version 22.0 and above , Is there any change in Version Specifiers Specifications ?

**Comment by pradyunsg** [comment]
Please see https://github.com/pypa/packaging/issues/530 (which is also a pinned issue).

**Comment by HarinadhD** [comment]
Got it , Thanks @pradyunsg
