### ISSUE TITLE
Metadata version checks breaks parsing setuptools

### ISSUE THREAD

**Issue by mweinelt** [pypa/packaging#855]
Hi!

After upgrading packaging to 24.2 we are seeing the following exception when parsing the wheel metadata for setuptools:

```
+ Exception Group Traceback (most recent call last):
|   File "/nix/store/vzvw9jjlrc5yzakk30g9d2sdj8cjxj2n-python-runtime-deps-check-hook.py", line 96, in <module>
|     metadata = get_metadata(args.wheel)
|                ^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/nix/store/vzvw9jjlrc5yzakk30g9d2sdj8cjxj2n-python-runtime-deps-check-hook.py", line 58, in get_metadata
|     metadata = Metadata.from_raw(raw)
|                ^^^^^^^^^^^^^^^^^^^^^^
|   File "/nix/store/12l10pnhkk9dpxxla7pcl6r2kz9mfgzw-python3.12-packaging-24.2/lib/python3.12/site-packages/packaging/metadata.py", line 752, in from_raw
|     raise ExceptionGroup("invalid metadata", exceptions)
| ExceptionGroup: invalid metadata (1 sub-exception)
+-+---------------- 1 ----------------
  | packaging.metadata.InvalidMetadata: license-file introduced in metadata version 2.4, not 2.1
  +------------------------------------
```

The `METADATA` file looks like this:

```
Metadata-Version: 2.1
Name: setuptools
Version: 75.3.0.post0
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Author-email: Python Packaging Authority <distutils-sig@python.org>
Project-URL: Source, https://github.com/pypa/setuptools
Project-URL: Documentation, https://setuptools.pypa.io/
Project-URL: Changelog, https://setuptools.pypa.io/en/stable/history.html
Keywords: CPAN PyPI distutils eggs package management
Classifier: Development Status :: 5 - Production/Stable
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: MIT License
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3 :: Only
Classifier: Topic :: Software Development :: Libraries :: Python Modules
Classifier: Topic :: System :: Archiving :: Packaging
Classifier: Topic :: System :: Systems Administration
Classifier: Topic :: Utilities
Requires-Python: >=3.8
Description-Content-Type: text/x-rst
License-File: LICENSE
Provides-Extra: certs
Provides-Extra: check
Requires-Dist: pytest-checkdocs>=2.4; extra == "check"
Requires-Dist: pytest-ruff>=0.2.1; sys_platform != "cygwin" and extra == "check"
Requires-Dist: ruff>=0.5.2; sys_platform != "cygwin" and extra == "check"
Provides-Extra: core
Requires-Dist: packaging>=24; extra == "core"
Requires-Dist: more-itertools>=8.8; extra == "core"
Requires-Dist: jaraco.text>=3.7; extra == "core"
Requires-Dist: wheel>=0.43.0; extra == "core"
Requires-Dist: platformdirs>=4.2.2; extra == "core"
Requires-Dist: jaraco.collections; extra == "core"
Requires-Dist: jaraco.functools; extra == "core"
Requires-Dist: packaging; extra == "core"
Requires-Dist: more-itertools; extra == "core"
Requires-Dist: importlib-metadata>=6; python_version < "3.10" and extra == "core"
Requires-Dist: tomli>=2.0.1; python_version < "3.11" and extra == "core"
Requires-Dist: importlib-resources>=5.10.2; python_version < "3.9" and extra == "core"
Provides-Extra: cover
Requires-Dist: pytest-cov; extra == "cover"
Provides-Extra: doc
Requires-Dist: sphinx>=3.5; extra == "doc"
Requires-Dist: jaraco.packaging>=9.3; extra == "doc"
Requires-Dist: rst.linker>=1.9; extra == "doc"
Requires-Dist: furo; extra == "doc"
Requires-Dist: sphinx-lint; extra == "doc"
Requires-Dist: jaraco.tidelift>=1.4; extra == "doc"
Requires-Dist: pygments-github-lexers==0.0.5; extra == "doc"
Requires-Dist: sphinx-favicon; extra == "doc"
Requires-Dist: sphinx-inline-tabs; extra == "doc"
Requires-Dist: sphinx-reredirects; extra == "doc"
Requires-Dist: sphinxcontrib-towncrier; extra == "doc"
Requires-Dist: sphinx-notfound-page<2,>=1; extra == "doc"
Requires-Dist: pyproject-hooks!=1.1; extra == "doc"
Requires-Dist: towncrier<24.7; extra == "doc"
Provides-Extra: enabler
Requires-Dist: pytest-enabler>=2.2; extra == "enabler"
Provides-Extra: ssl
Provides-Extra: test
Requires-Dist: pytest!=8.1.*,>=6; extra == "test"
Requires-Dist: virtualenv>=13.0.0; extra == "test"
Requires-Dist: wheel>=0.44.0; extra == "test"
Requires-Dist: pip>=19.1; extra == "test"
Requires-Dist: packaging>=23.2; extra == "test"
Requires-Dist: jaraco.envs>=2.2; extra == "test"
Requires-Dist: pytest-xdist>=3; extra == "test"
Requires-Dist: jaraco.path>=3.2.0; extra == "test"
Requires-Dist: build[virtualenv]>=1.0.3; extra == "test"
Requires-Dist: filelock>=3.4.0; extra == "test"
Requires-Dist: ini2toml[lite]>=0.14; extra == "test"
Requires-Dist: tomli-w>=1.0.0; extra == "test"
Requires-Dist: pytest-timeout; extra == "test"
Requires-Dist: pytest-home>=0.5; extra == "test"
Requires-Dist: pytest-subprocess; extra == "test"
Requires-Dist: pyproject-hooks!=1.1; extra == "test"
Requires-Dist: jaraco.test>=5.5; extra == "test"
Requires-Dist: jaraco.develop>=7.21; (python_version >= "3.9" and sys_platform != "cygwin") and extra == "test"
Requires-Dist: pytest-perf; sys_platform != "cygwin" and extra == "test"
Provides-Extra: type
Requires-Dist: pytest-mypy; extra == "type"
Requires-Dist: mypy==1.12.*; extra == "type"
Requires-Dist: importlib-metadata>=7.0.2; python_version < "3.10" and extra == "type"
Requires-Dist: jaraco.develop>=7.21; sys_platform != "cygwin" and extra == "type"

[...]

**Comment by abravalheri** [comment]
I am afraid this is not going to be fixed until we implement metadata version 2.3... which is being worked on, but will take some time.


Meanwhile, I suggest working around the problem (e.g. delete the field), or to not use `packaging` to parse setuptools-produced metadata.

**Comment by abravalheri** [comment]
If I am not wrong, the`packaging` module/classes also allow you to return the invalid fields instead of raising an exception. So that might be an option for working around the problem.

**Comment by mweinelt** [comment]
Yeah, looks like I can pass `validate=False` for now. Thank you!

**Comment by brettcannon** [comment]
Everyone is right here; the data validation is very strict when used, but it's entirely optional both from allowing for getting the raw data of being lazy about it. So I don't think there's a bug here.
