### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2

### ISSUE THREAD

**Issue by nitinmukesh** [pypa/packaging#861]
```
Searching for ninja==1.11.1.2
Best match: ninja 1.11.1.2
Processing ninja-1.11.1.2-py3.10-win-amd64.egg
ninja 1.11.1.2 is already the active version in easy-install.pth
>>>>>>>>>>>>>path c:\aii\ltx-video\venv\lib\site-packages\ninja-1.11.1.2-py3.10-win-amd64.egg\EGG-INFO\scripts\ninja.exe
Traceback (most recent call last):
  File "C:\aii\LTX-Video\q8_kernels\setup.py", line 222, in <module>
    setup(
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\dist.py", line 1217, in run_command
    super().run_command(command)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.run()
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\install.py", line 131, in do_egg_install
    cmd.run(show_deprecation=False)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 420, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 662, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 709, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 765, in process_distribution
    self.easy_install(dist.as_requirement())
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 681, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 712, in install_item
    self.process_distribution(spec, dists[0], deps, "Using")
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 735, in process_distribution
    self.install_egg_scripts(dist)
  File "C:\aii\LTX-Video\venv\lib\site-packages\setuptools\command\easy_install.py", line 611, in install_egg_scripts
    dist.get_metadata('scripts/' + script_name)
  File "C:\aii\LTX-Video\venv\lib\site-packages\pkg_resources\__init__.py", line 1435, in get_metadata
    return value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte in scripts/ninja.exe file at path: c:\aii\ltx-video\venv\lib\site-packages\ninja-1.11.1.2-py3.10-win-amd64.egg\EGG-INFO\scripts\ninja.exe
```

```
(venv) C:\aii\LTX-Video\q8_kernels>pip list
Package                Version
---------------------- ------------
accelerate             1.1.1
antlr4-python3-runtime 4.9.3
certifi                2024.8.30
charset-normalizer     3.4.0
colorama               0.4.6
contourpy              1.3.1
cycler                 0.12.1
diffusers              0.31.0
einops                 0.8.0
filelock               3.16.1
fonttools              4.55.2
fsspec                 2024.10.0
huggingface-hub        0.25.2
idna                   3.10
imageio                2.36.1
imageio-ffmpeg         0.5.1
importlib_metadata     8.5.0
Jinja2                 3.1.4
kiwisolver             1.4.7
MarkupSafe             3.0.2
matplotlib             3.9.3
mpmath                 1.3.0
networkx               3.4.2
ninja                  1.11.1.2
numpy                  2.1.3
omegaconf              2.3.0
packaging              24.2
pillow                 11.0.0
pip                    23.0.1
psutil                 6.1.0
pyparsing              3.2.0
python-dateutil        2.9.0.post0
PyYAML                 6.0.2
q8-kernels             0.0.0
regex                  2024.11.6
requests               2.32.3
safetensors            0.4.5
sentencepiece          0.2.0
setuptools             65.5.0
six                    1.17.0
sympy                  1.13.1
tokenizers             0.19.1
torch                  2.5.1+cu124
torchvision            0.20.1+cu124
tqdm                   4.67.1
transformers           4.44.2
typing_extensions      4.12.2
urllib3                2.2.3
zipp                   3.21.0

```

**Comment by brettcannon** [comment]
I'm not seeing 'packaging' in the traceback anywhere, so I don't think we are the cause of the error.
