### ISSUE TITLE
Error in requirements.py prevents mysqlclient package install

### ISSUE THREAD

**Issue by chrisspen** [pypa/packaging#94]
I'm trying to install the mysqlclient package in a virtualenv on a fresh Ubuntu 16, and when I run:

    pip install --cache-dir /tmp --no-binary mysqlclient mysqlclient

it fails with the traceback:

    Traceback (most recent call last):
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
        status = self.run(options, args)
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
        wb.build(autobuilding=True)
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
        self.requirement_set.prepare_files(self.finder)
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
        ignore_dependencies=self.ignore_dependencies))
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
        abstract_dist.prep_for_dist()
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
        self.req_to_install.run_egg_info()
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 412, in run_egg_info
        self.setup_py, self.name,
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
        import setuptools  # noqa
      File "/myproject/build/.env/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/myproject/build/.env/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/myproject/build/.env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
        import packaging.requirements
      File "/myproject/build/.env/local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
        MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
    TypeError: __call__() takes exactly 2 arguments (1 given)

[This SO answer](http://stackoverflow.com/a/41974462/247542) suggests it's a problem in requirements.txt, specifically on [this line](https://github.com/pypa/packaging/blob/master/packaging/requirements.py#L59), and recommends that:

    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")

should instead be changed to:

    MARKER_EXPR = originalTextFor(MARKER_EXPR(""))("marker")

**Comment by jaraco** [comment]
This issue stems from having an old version of pyparsing. This issue is a duplicate of #91. Install `pyparsing>=2.0.2` to work around the issue.

**Comment by chrisspen** [comment]
Thanks for the clarification. You're right, I was using pyparsing==2.0.1.
